In [2]:
pip install pgmpy

Collecting pgmpy
  Downloading pgmpy-0.1.24-py3-none-any.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 6.9 MB/s eta 0:00:00
Requirement already satisfied: numpy in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (1.23.5)
Requirement already satisfied: networkx in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (2.8.4)
Requirement already satisfied: joblib in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (1.1.1)
Requirement already satisfied: pandas in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (1.5.3)
Requirement already satisfied: pyparsing in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (3.0.9)
Requirement already satisfied: tqdm in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (4.64.1)
Requirement already satisfied: torch in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (1.12.1)
Requirement already satisfied: scipy in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (1.10.0)
Collecting opt-einsum
  Downloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     ---------------------------------------- 65.5/65.5 kB 3.7 MB/s eta 0:00:00
Requirement already satisfied: statsmodels in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (0.13.5)
Requirement already satisfied: scikit-learn in c:\users\siddhant\anaconda3\lib\site-packages (from pgmpy) (1.2.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\siddhant\anaconda3\lib\site-packages (from pandas->pgmpy) (2022.7)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\siddhant\anaconda3\lib\site-packages (from pandas->pgmpy) (2.8.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\siddhant\anaconda3\lib\site-packages (from scikit-learn->pgmpy) (2.2.0)
Requirement already satisfied: packaging>=21.3 in c:\users\siddhant\anaconda3\lib\site-packages (from statsmodels->pgmpy) (22.0)
Requirement already satisfied: patsy>=0.5.2 in c:\users\siddhant\anaconda3\lib\site-packages (from statsmodels->pgmpy) (0.5.3)
Requirement already satisfied: typing_extensions in c:\users\siddhant\anaconda3\lib\site-packages (from torch->pgmpy) (4.4.0)
Requirement already satisfied: colorama in c:\users\siddhant\anaconda3\lib\site-packages (from tqdm->pgmpy) (0.4.6)
Requirement already satisfied: six in c:\users\siddhant\anaconda3\lib\site-packages (from patsy>=0.5.2->statsmodels->pgmpy) (1.16.0)
Installing collected packages: opt-einsum, pgmpy
Successfully installed opt-einsum-3.3.0 pgmpy-0.1.24
Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy as np 
import pandas as pd
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator, BayesianEstimator
from pgmpy.inference import VariableElimination

In [2]:
data = pd.read_csv('heart.csv')
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [6]:
# keeping only imp features
new_df = data[['age', 'sex', 'cp', 'thalach', 'chol', 'target']]
new_df = new_df.iloc[:200, :]
new_df.head()

   age  sex  cp  thalach  chol  target
0   52    1   0      168   212       0
1   53    1   0      155   203       0
2   70    1   0      125   174       0
3   61    1   0      161   203       0
4   62    0   0      106   294       0

In [7]:
# Define the structure of your Bayesian network
model = BayesianModel([
    ('age', 'target'),
    ('sex', 'target'),
    ('cp', 'target'),
    ('thalach', 'target'),
    ('chol', 'target')
])

WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.

In [8]:
# Learn the parameters of the network from the data
model.fit(new_df, estimator=MaximumLikelihoodEstimator)

# Perform inference
inference = VariableElimination(model)

In [9]:
# You can now query the network for the probability of heart disease given some evidence
# Example evidence (you can replace this with actual patient data)
evidence = {
    'age': 67,
    'sex': 0,
    'cp': 2,
    'thalach': 150,
    'chol': 230
}

# Query the network
result = inference.query(variables=['target'], evidence=evidence)
print(result)

WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.

+-----------+---------------+
| target    |   phi(target) |
+===========+===============+
| target(0) |        0.5000 |
+-----------+---------------+
| target(1) |        0.5000 |
+-----------+---------------+